### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Jean-Serge** [Jean-Serge/charcount#1]
- [x] Count char occurency in a given string
- [ ] Accept any number of parameters
- [X] Correctly handle error
- [ ] Allow user to give a filename to read

**Comment by Jean-Serge** [comment]
The program correctly works with 1 parameters.
To pass it many words just put the sentence in `"`.

**Comment by Jean-Serge** [comment]
Error when no arguments is given has been handled.
